apiVersion: apps/v1
kind: Deployment
metadata:
  name: notejam-deployment
  labels:
    app: notejam
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notejam
  template:
    metadata:
      labels:
        app: notejam
    spec:
      containers:
      - name: notejam
        image: gasgurda/flask-demo
        ports:
        - containerPort: 5000
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: notejam-configmap
              key: ENVIRONMENT
        - name: SQLALCHEMY_DATABASE_URI
          valueFrom:
            configMapKeyRef:
              name: notejam-configmap
              key: SQLALCHEMY_DATABASE_URI
