apiVersion: apps/v1
kind: Deployment
metadata:
  name: notejam-deployment
  labels:
    app: notejam
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notejam
  template:
    metadata:
      labels:
        app: notejam
    spec:
      containers:
      - name: notejam
        image: gasgurda/notejam
        ports:
        - containerPort: 5000
