apiVersion: v1
kind: Pod
metadata:
  labels:
    run: postgresql
  name: postgresql
  namespace: default
spec:
  containers:
  - image: postgres-:13.4-alpine
    name: postgres
    ports:
    - containerPort: 5432
      protocol: TCP
