apiVersion: v1
kind: Pod
metadata:
  labels:
    run: postgresql
  name: postgresql
  namespace: default
spec:
  containers:
  - image: postgres:13.4-alpine
    name: postgres
    ports:
    - containerPort: 5432
      protocol: TCP
    env:
      - name: POSTGRES_DB
        valueFrom:
          configMapKeyRef:
            name: postgresql-configmap
            key: POSTGRES_DB
      - name: POSTGRES_USER
        valueFrom:
          configMapKeyRef:
            name: postgresql-configmap
            key: POSTGRES_USER
      - name: POSTGRES_PASSWORD
        valueFrom:
          configMapKeyRef:
            name: postgresql-configmap
            key: POSTGRES_PASSWORD
